eval:                # Evaluation metrics to log.
  keys:              # Metric keys to record for evaluation.
    - episode/return_mean
    - episode/return_std
    - episode/length_mean
    - episode/length_std
    - episode/score_mean
    - episode/score_min
    - episode/score_max
    - episode/wins
    - episode/win_rate
    - step/return_rate
    - step/score_rate
  termination: true  # Log termination cause counts/ratios.
train:               # Training metrics to log.
  keys:              # Metric keys to record for training.
    - episode/score_mean
    - episode/score_min
    - episode/score_max
    - episode/wins
    - episode/win_rate
  termination: true  # Log termination cause counts/ratios.
