defaults:
  - run: standard
  - board: classic
  - reward: standard
  - env: pov_pixel
  - feature_extractor: px_strided_cnn_l1k4
  - train: ppo
  - logging: standard
  - _self_

hydra:
  run:
    dir: .
  job:
    chdir: false
  output_subdir: null

