defaults:
  - run: default
  - board: classic
  - reward: default
  - env: head_pixel
  - feature_extractor: snake_pixel_cnn
  - train: ppo
  - metrics: default
  - logging: default
  - _self_

hydra:
  run:
    dir: .
  job:
    chdir: false
  output_subdir: null



