defaults:
  - run: default
  - board: small
  - reward: default
  - env: world_tile_id
  - feature_extractor: tile_mlp
  - train: ppo
  - logging: default
  - _self_

run:
  name: world_tile_mlp_large



