defaults:
  - run: standard
  - board: small
  - reward: standard
  - env: global_tile_id
  - feature_extractor: tile_mlp
  - train: ppo
  - logging: standard
  - _self_

run:
  name: global_tile_mlp_large

