defaults:
  - run: default
  - board: small
  - reward: default
  - env: head_categorical
  - feature_extractor: snake_categorical_vit
  - train: ppo
  - logging: default
  - _self_

run:
  name: head_categorical_vit_small



