defaults:
  - run: standard
  - level: small
  - reward: standard
  - env: pov_tile_id
  - feature_extractor: tile_vit
  - train: ppo
  - logging: standard
  - _self_

run:
  name: pov_tile_vit_small
