defaults:
  - run: standard
  - board: small
  - reward: standard
  - env: pov_pixel
  - feature_extractor: px_strided_cnn_l1k4
  - train: ppo
  - logging: standard
  - _self_

run:
  name: pov_pixel_ppo

