defaults:
  - run: default
  - board: small
  - reward: default
  - env: head_tile_id
  - feature_extractor: tile_vit
  - train: ppo
  - logging: default
  - _self_

run:
  name: head_tile_vit_small



