defaults:
  - run: default
  - board: small
  - reward: default
  - env: world_categorical
  - feature_extractor: snake_categorical_mlp
  - train: ppo
  - logging: default
  - _self_

run:
  name: world_categorical_mlp_large



