defaults:
  - run: default
  - board: small
  - reward: default
  - env: head_pixel
  - feature_extractor: snake_pixel_cnn
  - train: ppo
  - logging: default
  - _self_

run:
  name: head_pixel_ppo



